# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01970c02ac44a088c64cc1b0770b54f57bb929edb57f3b92b097f920056592fa9c1a3a6e916517daa586f88765db4d961b21089b460524c974eb35e0068455ec

test:
  secret_key_base: 11e469e7048be49058b07ad4d28c8b3b4f0c0312960f2cddbfc0daa556a80a1e4b93fbba3f2bb39158ab438a23893d4b50a8f31c560a3017f3fc9472edfe5de1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
